# Image Analyst
from .image_analyst_prompt import (
    IMAGE_ANALYST_SYSTEM_PROMPT,
    IMAGE_ANALYST_USER_PROMPT,
    IMAGE_ANALYST_WITH_TEXT_PROMPT,
)

# Diet Analyst
from .diet_analyst_prompt import (
    DIET_ANALYST_SYSTEM_PROMPT,
    DIET_ANALYST_USER_PROMPT,
    DIET_ANALYST_WITH_USER_PROMPT,
)

# Exercise Analyst
from .exercise_analyst_prompt import (
    EXERCISE_ANALYST_SYSTEM_PROMPT,
    EXERCISE_ANALYST_USER_PROMPT,
    EXERCISE_ANALYST_WITH_USER_PROMPT,
)

# Health Manager
from .health_manager_prompt import (
    HEALTH_MANAGER_SYSTEM_PROMPT,
    HEALTH_MANAGER_EXTRACT_PROMPT,
    HEALTH_MANAGER_RECOMMENDATION_PROMPT,
)

# Router
from .router_prompt import (
    ROUTER_SYSTEM_PROMPT,
    ROUTER_CLASSIFY_PROMPT,
)

__all__ = [
    # Image Analyst
    "IMAGE_ANALYST_SYSTEM_PROMPT",
    "IMAGE_ANALYST_USER_PROMPT",
    "IMAGE_ANALYST_WITH_TEXT_PROMPT",
    # Diet Analyst
    "DIET_ANALYST_SYSTEM_PROMPT",
    "DIET_ANALYST_USER_PROMPT",
    "DIET_ANALYST_WITH_USER_PROMPT",
    # Exercise Analyst
    "EXERCISE_ANALYST_SYSTEM_PROMPT",
    "EXERCISE_ANALYST_USER_PROMPT",
    "EXERCISE_ANALYST_WITH_USER_PROMPT",
    # Health Manager
    "HEALTH_MANAGER_SYSTEM_PROMPT",
    "HEALTH_MANAGER_EXTRACT_PROMPT",
    "HEALTH_MANAGER_RECOMMENDATION_PROMPT",
    # Router
    "ROUTER_SYSTEM_PROMPT",
    "ROUTER_CLASSIFY_PROMPT",
]
